const DUPLICATE_GARAGE_SECTION = {
  canHide: true,
  fields: [
    {
      display: 'PM Notes',
      name: 'garage_23PmNote',
      type: 'textarea',
    },
    {
      display: 'Garage Door',
      hint: true,
      items: [
        {
          display: 'Futura - Smooth',
          id: 'futuraSmooth',
          url: '/assets/img/futura.png',
        },
        {
          display: 'Futura - W/grain',
          id: 'futuraWoodGrain',
          url: '/assets/img/futura.png',
        },
        {
          display: 'Milano - Smooth',
          id: 'milanoSmooth',
          url: '/assets/img/milano.jpeg',
        },
        {
          display: 'Milano - W/grain',
          id: 'milanoWoodGrain',
          url: '/assets/img/milano.jpeg',
        },
        {
          display: 'Valero',
          id: 'valero',
          url: '/assets/img/valero.png',
        },
        {
          display: 'Other - Please Specify',
          id: 'other',
          url: '',
        },
      ],
      name: 'garageDoor',
      type: 'image-picker',
    },
    {
      display: 'Colour',
      items: [
        {
          display: 'TBC',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/tbc.png',
          id: 'tbc',
        },
        {
          display: 'Desert sand',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/desert-sand.png',
          id: 'desertSand',
        },
        {
          display: 'Ebony',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/ebony.png',
          id: 'ebony',
        },
        {
          display: 'Flax Pod',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/flax-pod.png',
          id: 'flaxPod',
        },
        {
          display: 'Grey friars',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115841/colours/exterior/grey-friars.png',
          id: 'greyFriars',
        },
        {
          display: 'Gull grey',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/gull-grey.png',
          id: 'gullGrey',
        },
        {
          display: 'Ironsand',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/ironsand.png',
          id: 'ironsand',
        },
        {
          display: 'Karaka',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115841/colours/exterior/karaka.png',
          id: 'karaka',
        },
        {
          display: 'Lignite',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115841/colours/exterior/lignite.png',
          id: 'lignite',
        },
        {
          display: 'Mist green',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115841/colours/exterior/mist-green.png',
          id: 'mistGreen',
        },
        {
          display: 'New denim blue',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614116586/colours/joinery/matt-new-denim-blue.jpg',
          id: 'newDenimBlue',
        },
        {
          display: 'Permanent green',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115841/colours/exterior/permanent-green.png',
          id: 'permanentGreen',
        },
        {
          display: 'Sandstone grey',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/sandstone-grey.png',
          id: 'sandstoneGrey',
        },
        {
          display: 'Scoria',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115839/colours/exterior/scoria.png',
          id: 'scoria',
        },
        {
          display: 'Thunder grey',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/thunder-grey.png',
          id: 'thunderGrey',
        },
        {
          display: 'Titania',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/titania.png',
          id: 'titania',
        },
        {
          display: 'Windsor grey',
          url: 'https://res.cloudinary.com/venture/image/upload/v1614115840/colours/exterior/windsor-grey.png',
          id: 'windsorGrey',
        },
        {
          display: 'Other - Please Specify',
          url: '',
          id: 'other',
        },
      ],
      name: 'garageColour',
      type: 'image-picker',
    },
    {
      display: 'GDoor Insulation',
      items: ['No', 'Single', 'Single + Half', 'Double', 'Other - Please Specify'],
      name: 'garageDoorInsulation',
      type: 'dropdown',
    },
    {
      display: 'GDoor Jamb',
      items: ['Aluminium', 'Timber', 'Other - Please Specify'],
      name: 'garageDoorJamb',
      type: 'dropdown',
    },
    {
      display: 'Jamb Colour',
      name: 'garageDoorJambColour',
      type: 'text',
    },
    {
      display: 'Attic Ladder',
      hint: true,
      items: ['Yes', 'No', 'Other - Please Specify'],
      name: 'atticLadder',
      type: 'dropdown',
    },
    {
      display: 'Additional Info',
      name: 'garage_additional',
      type: 'textarea',
    },
  ],
  garageColour: 'desertSand',
  garageDoor: 'futuraSmooth',
  garageDoor_hint: 'Horizontal Ribbed profile - 3x deep ribs & 2x fine "pencil" ribs per panel.',
  garage_additional: 'new garage info',
  hasExtras: true,
  id: 23,
  name: 'garage_23',
  title: 'New Garage',
  type: 'DUPLICATE',
};

const SWIMMING_POOL_FREE_TEXT_SECTION = {
  attachImage_additional: 'comes with pool cleaning robot',
  canHide: true,
  fields: [
    {
      display: 'PM Notes',
      name: 'swimmingpool_22PmNote',
      type: 'textarea',
    },
    {
      display: '',
      maxRows: 15,
      minRows: 13,
      name: 'attachImage_additional',
      type: 'textarea',
    },
  ],
  hasExtras: true,
  id: 22,
  name: 'swimmingpool_22',
  title: 'Swimming Pool',
  type: 'FREE',
};

const SPEC = {
  hiddenSections: {},
  'cladding-additional': {
    '0': {
      area: 'As per plan',
      claddingType: 'JH Linea WB 180mm cover',
      colour1: 'Double Foundry',
      lrv1: '6',
    },
    '1': {
      area: 'As per plan',
      claddingType: 'JH Linea WB 180mm cover',
      colour1: 'Double Foundry',
      lrv1: '6',
      mortarColour: 'Coloured to match',
      mortarColour_hint: 'Mortar to match brick colour additional $400 (POA)',
    },
    '2': {
      area: 'Outdoor Bar',
      facingsAndScribers: 'Rounded Scriber (std)',
    },
  },
  details: {
    status: 'Quote',
    lastModified: Date.now(),
  },
  contact_details: {
    client: 'Mr Cantona',
    emails: ['client@email.com'],
    phones: [123456789],
    consultantName: 'Randall Bouverie',
    consultantEmail: 'share@email.com',
    consultantPhone: '11111',
    projectManagerEmail: 'darren.merrick@venturedevelopments.co.nz',
    projectManagerName: 'Darren Merrick',
    projectManagerPhone: '0274698318',
    quantitySurveyorEmail: 'kaelin.clark@venturedevelopments.co.nz',
    quantitySurveyorName: 'Kaelin Clark',
  },
  ensuite: {
    enduroShield: 'Yes',
    toilet: 'etonS15',
  },
  garage: {
    atticLadder: 'Yes',
    atticLadder_hint: 'Includes 2 x kopine floor sheets',
    dummy: ' ',
    garageColour: 'flaxPod',
    garageDoor: 'futuraSmooth',
    garageDoorInsulation: 'No',
    garageDoorJamb: 'Timber',
    garageDoorJambColour: 'Double Foundry',
  },
  mainBathroom: {
    bath: 'no bath',
    dummy: ' ',
    enduroShield: 'No',
    floorAdditionalInfo: 'Layout & Direction: Stack bond (STD) any changes are (POA). Handless vanity.',
    floorType: 'Tiled',
    heatedTowelRail: 'alexSquare',
    houseSize_hint: 'SQM over frame',
    mainFloorColour: 'Industry Grigio 60',
    mainFloorLayout: 'Standard',
    mainFloorType: 'Porcelain',
    mainVanityColour: 'Industry Grigio',
    mainVanityGrout: 'To match tile',
    mainVanityLayout: '150mm high',
    mainVanityTile: 'Porcelain',
    mirrorVanity: '900 High with tiled splashback',
    mouldedWall: 'mouldedWall',
    shower: 'acrylic1000Cnr',
    showerMixer: 'hansaPinto',
    showerSlide: 'Std',
    skirting: 'Tiled',
    skirtingColour: 'Industry Grigio',
    toilet: 'vitraS50',
    toiletRollHolder: 'gessaModern',
    undefined: '',
    vanity: 'Venture S50 double draw neg detail handles ',
    vanityColour: 'White',
    vanityMixer: 'hansaPinto',
    vanityPmNote: '',
    vanitySplashback: 'Tiled - other',
  },
  section_details: {
    lot: 'Lot',
    scheme: 'Scheme 2',
    subdivision: 'GreenFields',
  },
  quote: {
    paymentMethod: [
      {
        date: 'Fri Jun 26 2020 11:39:31 GMT+1200 (New Zealand Standard Time)',
        user: 'rich@blacksandsolutions.co',
        value: 'Turnkey Payment method',
      },
    ],
  },
  swimmingpool_22: SWIMMING_POOL_FREE_TEXT_SECTION,
  garage_23: DUPLICATE_GARAGE_SECTION,
};

const ORDER_LIST = [
  'section_details',
  'garage',
  'planning',
  'mainBathroom',
  'swimmingpool_22',
  'garage_23',
  'layout',
  'exterior',
  'cladding',
  'joinery',
  'insulation',
  'interior',
  'kitchen',
  'appliances',
  'laundry',
  'toilet',
  'ensuite',
  'floor',
  'electrical',
  'blinds',
  'homeware',
  'landscape',
];

export { SPEC, ORDER_LIST };
