export const environment = {
  production: true,
  serviceWorker: true,
  enableProdMode: true,
  env: 'PROD',
  version: 'APP_VERSION',
  commit: 'CI_COMMIT_ID',
  build: 'CI_BUILD_URL',
  jobCreatedEmailTemplateId: '',
  jobUpdatedEmailTemplateId: '',
  remedialCreatedEmailTemplateId: '',
  remedialUpdatedEmailTemplateId: '',
  remedialSubmittedEmailTemplateId: '',
  shareFilesEmailTemplateId: '',
  shareSpecEmailTemplateId: '',
};
