const floorTypes = ['Carpet', 'Tiles', 'Vinyl Planking', 'Timber Laminate', 'Polished Concrete', 'Other - Please Specify'];

export const floorConfig = {
  id: 16,
  name: 'floor',
  title: 'Floor Coverings',
  canDuplicate: true,
  canHide: true,
  hasCustom: true,
  hasExtras: true,
  fields: [
    { name: 'floorPmNote', display: 'PM Notes', type: 'textarea' },
    { text: 'Carpet', type: 'subtitle', name: 'carpetSubTitle' },
    { name: 'carpetPmNote', display: 'PM Notes', type: 'textarea', canHide: 'carpetSubTitle' },
    {
      name: 'floorType',
      display: 'Floor Type',
      items: ['Solution Dyed Nylon', 'Wool', 'Other - Please Specify'],
      type: 'dropdown',
      canHide: 'carpetSubTitle',
    },
    {
      name: 'underlay',
      display: 'Underlay',
      items: ['High density 10 mm', 'High density 11mm', 'Other - Please Specify'],
      type: 'dropdown',
      canHide: 'carpetSubTitle',
    },
    { name: 'range', display: 'Range', type: 'text', canHide: 'carpetSubTitle' },
    { name: 'floorColour', display: 'Colour', type: 'text', canHide: 'carpetSubTitle' },
    {
      name: 'garageCarpet',
      display: 'Garage Carpet',
      items: ['No', 'Single', 'Double', 'Other - Please Specify'],
      type: 'dropdown',
      canHide: 'carpetSubTitle',
    },
    { name: 'floor_additional', display: 'Additional Info', type: 'textarea', canHide: 'carpetSubTitle' },

    {
      name: 'flooring-additional',
      display: 'Flooring Groups',
      title: 'Additional Floor Coverings',
      type: 'custom-blocks',
      default: { floorTypes: 'Carpet' },
      blockFields: [
        {
          name: 'flooringadditionalPmNote',
          display: 'PM Notes',
          type: 'textarea-pm',
          fullWidth: true,
          order: 0,
          canHide: 'flooring-additional',
        },
        {
          name: 'floorTypes',
          display: 'Floor Type',
          items: floorTypes,
          type: 'dropdown',
          order: 1,
          canHide: 'flooring-additional',
        },
        {
          name: 'type',
          display: 'Type',
          type: 'text-conditional',
          order: 2,
          condition: {
            field: 'floorTypes',
            value: '!Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'colour',
          display: 'Colour',
          type: 'text-conditional',
          order: 3,
          condition: {
            field: 'floorTypes',
            value: '!Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'details',
          display: 'Details',
          type: 'textarea-conditional',
          fullWidth: true,
          order: 4,
          condition: {
            field: 'floorTypes',
            value: '!Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'tileType',
          display: 'Tile Type',
          type: 'text-conditional',
          order: 2,
          condition: {
            specVersion: '1.0',
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'tileColour',
          display: 'Tile Colour',
          type: 'text-conditional',
          order: 3,
          condition: {
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'groutColour',
          display: 'Grout Colour',
          type: 'text-conditional',
          order: 4,
          condition: {
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'tileLayout',
          display: 'Tile Layout',
          type: 'text-conditional',
          order: 5,
          condition: {
            specVersion: '1.0',
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'tileLayout',
          display: 'Tile Layout',
          type: 'dropdown',
          items: ['Stacked', 'Bricklayed', 'Other - Please specify'],
          order: 5,
          condition: {
            specVersion: '2.01+',
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
        {
          name: 'additionalInfo',
          display: 'Additional info',
          type: 'textarea-conditional',
          fullWidth: true,
          order: 6,
          condition: {
            field: 'floorTypes',
            value: 'Tiles',
          },
          canHide: 'flooring-additional',
        },
      ],
    },
  ],
};
