export const packages = {
  standardSmall: [
    '16x LED Energy Star down lights',
    '7x Single Gang light switches',
    '3x Task lights / Pendants above bench',
    '1x Double Gang light switches',
    '4x external bulkhead lights',
    '2x Triple Gang light switches',
    '1x Sensor spot light',
    '0x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '2x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '1x 3-way switching',
    '12x Double power points',
    '1x Sky / Freeview master point',
    '1 x Sky / Freeview secondary point',
    '1x Dishwaster/Wastemaster Double point',
    '1x Phone/Data point',
    '1x Data Box Double point',
    '1x Internal switch board with RCD protection',
    '1x Washing machine / Dryer Double point',
    '15m Mains cable',
    '1x Fridge Single point',
    '10m Sub mains cable (single phase)',
    '1x Microwave Single point',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '1x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1x Full testing and compliance cert.'
  ],
  standardMedium: [
    '22x LED Energy Star down lights',
    '10x Single Gang light switches',
    '3x Task lights / Pendants above bench',
    '4x Double Gang light switches',
    '4x external bulkhead lights',
    '1x Triple Gang light switches',
    '1x Sensor spot light',
    '0x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '3x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '0x 3-way switching',
    '16x Double power points',
    '1x Sky / Freeview master point',
    '1x Dishwaster/Wastemaster Double point',
    '1x Sky / Freeview secondary point',
    '1x Data Box Double point',
    '2x Phone/Data point',
    '1x Washing machine / Dryer Double point',
    '1x Internal switch board with RCD protection',
    '1x Fridge Single point',
    '15m Mains cable',
    '1x Microwave Single point',
    '10m Sub mains cable (single phase)',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '2x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1 x Full testing and compliance cert'
  ],
  standardLarge: [
    '33x LED Energy Star down lights',
    '15x Single Gang light switches',
    '3x Task lights / Pendants above bench',
    '2x Double Gang light switches',
    '6x external bulkhead lights',
    '0x Triple Gang light switches',
    '1x Sensor spot light',
    '2x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '4x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '0x 3-way switching',
    '23x Double power points',
    '1x Sky / Freeview master point',
    '1x Dishwaster/Wastemaster Double point',
    '2x Sky / Freeview secondary point',
    '1x Data Box Double point',
    '2x Phone/Data point',
    '1x Washing machine / Dryer Double point',
    '1x Internal switch board with RCD protection',
    '1x Fridge Single point',
    '15m Mains cable',
    '1x Microwave Single point',
    '10m Sub mains cable (single phase)',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '2x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1x Full testing and compliance cert.'
  ]
};

export const packagesV3 = {
  standardSmall: [
    '16x LED Energy Star down lights',
    '7x Single Gang light switches',
    'Complimentary installation of up to three pendant/task lights lights included',
    '1x Double Gang light switches',
    '4x external bulkhead lights',
    '2x Triple Gang light switches',
    '1x Sensor spot light',
    '0x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '2x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '1x 3-way switching',
    '12x Double power points',
    '1x Sky / Freeview master point',
    '1 x Sky / Freeview secondary point',
    '1x Dishwaster/Wastemaster Double point',
    '1x Phone/Data point',
    '1x Data Box Double point',
    '1x Internal switch board with RCD protection',
    '1x Washing machine / Dryer Double point',
    '15m Mains cable',
    '1x Fridge Single point',
    '10m Sub mains cable (single phase)',
    '1x Microwave Single point',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '1x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1x Full testing and compliance cert.'
  ],
  standardMedium: [
    '22x LED Energy Star down lights',
    '10x Single Gang light switches',
    'Complimentary installation of up to three pendant/task lights lights included',
    '4x Double Gang light switches',
    '4x external bulkhead lights',
    '1x Triple Gang light switches',
    '1x Sensor spot light',
    '0x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '3x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '0x 3-way switching',
    '16x Double power points',
    '1x Sky / Freeview master point',
    '1x Dishwaster/Wastemaster Double point',
    '1x Sky / Freeview secondary point',
    '1x Data Box Double point',
    '2x Phone/Data point',
    '1x Washing machine / Dryer Double point',
    '1x Internal switch board with RCD protection',
    '1x Fridge Single point',
    '15m Mains cable',
    '1x Microwave Single point',
    '10m Sub mains cable (single phase)',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '2x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1 x Full testing and compliance cert'
  ],
  standardLarge: [
    '33x LED Energy Star down lights',
    '15x Single Gang light switches',
    'Complimentary installation of up to three pendant/task lights lights included',
    '2x Double Gang light switches',
    '6x external bulkhead lights',
    '0x Triple Gang light switches',
    '1x Sensor spot light',
    '2x Quad Gang light switches',
    '1x Dual Tube 5ft Fluorescent light',
    '4x 2-way switching',
    '1x Heat / Light / Fan unit with 4 gang switch per bathroom',
    '0x 3-way switching',
    '23x Double power points',
    '1x Sky / Freeview master point',
    '1x Dishwaster/Wastemaster Double point',
    '2x Sky / Freeview secondary point',
    '1x Data Box Double point',
    '2x Phone/Data point',
    '1x Washing machine / Dryer Double point',
    '1x Internal switch board with RCD protection',
    '1x Fridge Single point',
    '15m Mains cable',
    '1x Microwave Single point',
    '10m Sub mains cable (single phase)',
    '1x Garage Door Single point',
    '1x Phone line and Duct',
    '1x Rangehood Single point',
    '1x Inspection and connection to grid',
    '2x Heated Towel Rail connection',
    '1x Builders Temporary Supply',
    '1x Hot water Connection (cylinder or infinity)',
    '1x Internal Meter box and Main earth',
    '1x 25 amp Hob and Oven connection',
    '1x Star wiring data box',
    'Aerial Cabling as required (Note: no aerial installed - owners care)',
    '1x Full testing and compliance cert.'
  ]
};
